#!/bin/sh
CUR_DIR=$(pwd)
ADD_LANG_DIR=`dirname $0`
cd $ADD_LANG_DIR
OHOME=%ORACLE_HOME%
OHOMENAME=%ORACLE_HOME_NAME%
./runInstaller -addLangs ORACLE_HOME=$OHOME ORACLE_HOME_NAME=$OHOMENAME $* 
cd $CUR_DIR
